# Generated by Django 5.1 on 2024-08-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0002_personn'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='city',
            field=models.CharField(default='Inconnue', max_length=50),
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.CharField(default='Non spécifiée', max_length=50),
        ),
        migrations.AddField(
            model_name='eleve',
            name='date_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='eleve',
            name='registration',
            field=models.CharField(default='000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=10),
        ),
    ]
